trainer:
    accelerator : 'gpu'
    precision: 16-mixed
    min_epochs: 6
    max_epochs: 100
    benchmark: True
    log_every_n_steps: 10
learning:
    model: "unet"
    loss: "ce"
    backbone: "resnet18"
    weights: True  # imagenet weights
    in_channels: 4  # RGB+DEM
    num_classes: 16
    lr: 1e-3
    patience: 6
    ignore_index: 0  # classes 0 & 15 are not used in scoring
datamodule:
    root_dir: "/fastdata/acc19jc/mveo-dataset"
    train_coordinate_file_path: "train_coordinate_list.txt"
    # 1% =~ 770, 10% =~ 7700, 25% =~ 19000, 50% =~ 38500
    training_sample_amount: 770  # 77133 is the total number of training samples
    val_image_file_path: "val_image_list.txt"
    batch_size: 64
    num_workers: 1
    patch_size: 256
